export const allData = {
  mockIds: [
    "lJlEQim-yMo",
    "8R_7KCtShkU",
    "_8JtnUpkP0s",
    "B_8P6wfZchE",
    "te61SP-KHBs",
    "EKkzbbLYPuI",
    "n7VHYBkCbF4",
    "mcD9_hkZ7d8",
    "EgnqSKptayI",
    "zJY_JnSkMrc",
    "h4T_LlK1VE4",
    "_bptrMV3zHE",
    "ORDVCeBjJdM",
    "SJOKlqJho8U",
    "61AMlHqtr-w",
    "CyqctquwO3Y",
    "c5wMO2WSEVs",
    "Xl_FNnxF7b8",
    "llFT7vcp8o0",
    "ng9dtd6qwuM",
    "qRRuOTuhL_o",
    "GOMkFOjROSg",
    "o0etimvtD74",
    "lvZBGJkbeTE",
    "cOU17LDTVNo",
    "kmRhy2gLclI",
    "QWdW2x_O6mQ",
    "L_REGt4Vktk",
    "jbX0TwPQ1Ew",
    "ODeqcpWrx3o",
    "mbA1HobcD9I",
    "bGU6GNgFrhc",
    "ZdfNUxI4xgI",
    "5qap5aO4i9A",
    "WsptdUFthWI",
    "PmEJs9VS9jE",
    "S4mfSCtfKCA",
    "WGBYBV2MPnI",
    "R9P8PcuL6RU",
    "EY-SSAljYa4",
    "s1EyijVNx2M",
    "hMrk1VNBub8",
    "ESe380Q9New",
    "dysdU3zFOnE",
    "CGg8FzDAt9w",
    "jXZAbnn1kTU",
    "2Ieg3yFcaaw",
    "RyHo15EyGcE",
    "1mI3vkuIEj8",
    "lA1ItxM9yIE",
    "RRcgqBNuoXc",
    "_77HS_NS4Co",
    "nYn1RZR_ph4",
    "N8lCEJo1y5g",
    "bUvZNpFLtGs",
    "tA5giyG8E7g",
    "bVq7snH0ulo",
    "6L-WhdPBaiE",
    "UgHKb_7884o",
    "0MW0mDZysxc",
    "z5LS4kqJjKo",
    "sjoepLlVL6o",
    "shoVsQhou-8",
    "2-Sw86fddpY",
    "KW8fGRTFWKc",
    "wlsdMpnDBn8",
    "B5E3IKF9HPs",
    "hgdSJdeGF_0",
    "WRC78QhtCbE",
    "48CuhRAjLyE",
    "88aDJFdUjH4",
    "BUxBP0zS1pE",
  ],

  mockInfo: [
    {
      link: "https://www.youtube.com/watch?v=lJlEQim-yMo",
      id: "lJlEQim-yMo",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/lJlEQim-yMo/maxresdefault.jpg",
      title: "Relaxing Christmas Jazz Music 10 Hours",
      creator: "Relax Cafe Music",
      views: 4468709,
      description:
        "he Best Compilation of Relaxing, Soothing Traditional Christmas Jazz Melodies for Full 10 Hours! Music by Richard Freeman. Playlist:Aunl Lang Syne Jazz Silen...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=8R_7KCtShkU",
      id: "8R_7KCtShkU",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/8R_7KCtShkU/maxresdefault.jpg",
      title: "Fastest cat slaps",
      creator: "JAVIER GUTIERREZ",
      views: 8478317,
      description: "My crazy cats",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=_8JtnUpkP0s",
      id: "_8JtnUpkP0s",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/_8JtnUpkP0s/maxresdefault.jpg",
      title: "A Complete Fail at Getting Marijuana - Key & Peele",
      creator: "Key \\u0026 Peele",
      views: 4573164,
      description:
        "This guy is really bad at procuring medical marijuana.About Key & Peele: Key & Peele showcases the fearless wit of stars Keegan-Michael Key and Jordan Peele ...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=B_8P6wfZchE",
      id: "B_8P6wfZchE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/B_8P6wfZchE/hqdefault.jpg",
      title: "Baby Yoda being ADORABLE with subtitles again",
      creator: "agameofantasy",
      views: 9323055,
      description:
        "I got such great feedback from the first Baby Yoda being adorable with subtitles video, so I made another one! Working on a Mando tribute and can't wait to s...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=te61SP-KHBs",
      id: "te61SP-KHBs",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/te61SP-KHBs/maxresdefault.jpg",
      title:
        "Try not to Laugh or Grin at HARDSTOP LUCAS Funny Instagram Videos 2018 #6",
      creator: "AlotVines",
      views: 10247378,
      description:
        "Try not to laugh or grin while watching Hardstop Lucas Funny Instagram Videos 2018Part 1 - https://youtu.be/8zU7FmGcJ6gPart 2 - https://youtu.be/GYj-hqUi_VUP...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=EKkzbbLYPuI",
      id: "EKkzbbLYPuI",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/EKkzbbLYPuI/maxresdefault.jpg",
      title: "Lindsey Stirling - Carol of the Bells (Official Video)",
      creator: "Lindsey Stirling",
      views: 51692433,
      description:
        "Stream/Download ‘Lose You Now’ here: https://found.ee/LS_LoseYouNowMy new album #Artemis is out now! https://found.ee/LS_ArtemisCome see me on the #ArtemisTo...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=n7VHYBkCbF4",
      id: "n7VHYBkCbF4",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/n7VHYBkCbF4/maxresdefault.jpg",
      title:
        "Billie Eilish: The World’s A Little Blurry - Official Trailer | Apple TV+",
      creator: "Billie Eilish",
      views: 4196098,
      description:
        'Witness the incredible rise of Billie Eilish in "Billie Eilish: The World’s A Little Blurry” as she tours and records the album that changes her life. Watch ...',
      durationSeconds: undefined,
    },
    {id: "mcD9_hkZ7d8", errorMessage: "Video does not exist"},
    {
      link: "https://www.youtube.com/watch?v=EgnqSKptayI",
      id: "EgnqSKptayI",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/EgnqSKptayI/maxresdefault.jpg",
      title:
        'Character Teaser - "Albedo: Still Life and Creation" | Genshin Impact',
      creator: "Genshin Impact",
      views: 3046655,
      description:
        'Master Albedo is an artist of rare talent. His strokes are subtle, and he weaves his alchemy into them.But... surely, he has surpassed "craft" and entered th...',
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=zJY_JnSkMrc",
      id: "zJY_JnSkMrc",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/zJY_JnSkMrc/maxresdefault.jpg",
      title: "Developer Update | Kanezaka | Overwatch",
      creator: "PlayOverwatch",
      views: 666588,
      description:
        "Game Director Jeff Kaplan discusses Overwatch's newest Free-For-All map, Kanezaka, and gives a quick end-of-year recap.  ESRB Rating: TEEN with Blood, Use of...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=h4T_LlK1VE4",
      id: "h4T_LlK1VE4",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/h4T_LlK1VE4/maxresdefault.jpg",
      title: "Glitterbomb 3.0 vs. Porch Pirates",
      creator: "Mark Rober",
      views: 32557917,
      description:
        "Merry Christmas ya filthy animals.  If you want to learn the design fundamentals it takes to make something like the Glitter Bomb, enroll in my NEW Creative ...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=_bptrMV3zHE",
      id: "_bptrMV3zHE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/_bptrMV3zHE/hqdefault.jpg",
      title: "Yung Bleu - You're Mines Still (feat. Drake) [Official Video]",
      creator: "Yung Bleu",
      views: 66042595,
      description: `The official video for "You're Mines Still feat. Drake" out now: https://OVOSOUND.lnk.to/YoureMinesStillMore Yung Bleu:Insta: https://www.instagram.com/bleuv...`,
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=ORDVCeBjJdM",
      id: "ORDVCeBjJdM",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/ORDVCeBjJdM/maxresdefault.jpg",
      title:
        "@Grupo Firme   - @El Mimoso   -Deja - El Flaco - El Yaki - Grupo Codiciado - (Official Video)",
      creator: "Grupo Firme",
      views: 8861643,
      description:
        "Music video by Grupo Firme performing - Deja -. © 2020 Isael Gutierrez & Evert Gutierrez , Exclusive License To Music Vip Entertainment .Suscribete Aqui http...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=SJOKlqJho8U",
      id: "SJOKlqJho8U",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/SJOKlqJho8U/maxresdefault.jpg",
      title: "The Kid LAROI - WITHOUT YOU (Official Video)",
      creator: "The Kid LAROI.",
      views: 27928847,
      description:
        'Official video for "WITHOUT YOU" by The Kid LAROI. Listen & Download "F*CK LOVE (SAVAGE)" out now: https://TheKidLaroi.lnk.to/SavageExecutive Produced By: Gr...',
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=61AMlHqtr-w",
      id: "61AMlHqtr-w",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/61AMlHqtr-w/hqdefault.jpg",
      title: "Sheff G - Mistakes (Official Video Release)",
      creator: "Sheff G",
      views: 1867638,
      description:
        'Order “Proud Of Me Now" https://smarturl.it/ProudOfMeNowSubscribe To Sheff G on YouTube: https://smarturl.it/SheffGYTSubDirected by Nimi Hendrix, Azae Produc...',
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=CyqctquwO3Y",
      id: "CyqctquwO3Y",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/CyqctquwO3Y/maxresdefault.jpg",
      title: "BLACKPINK - ‘THE SHOW’ POSTPONEMENT ANNOUNCEMENT",
      creator: "BLACKPINK",
      views: 3730507,
      description:
        "BLACKPINK: THE SHOW now has a NEW DATEYG PALM STAGE - 2021 BLACKPINK: THE SHOW🌍 2021.01.31 2PM (KST)🌍 Livestream on YouTubeBuy Access @ https://yt.be/music...",
      durationSeconds: undefined,
    },
    {id: "c5wMO2WSEVs", errorMessage: "Video does not exist"},
    {
      link: "https://www.youtube.com/watch?v=Xl_FNnxF7b8",
      id: "Xl_FNnxF7b8",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/Xl_FNnxF7b8/maxresdefault.jpg",
      title: "OFFLINETV GINGERBREAD HOUSE BUILDING CONTEST",
      creator: "OfflineTV",
      views: 2620888,
      description:
        "NEW CHRISTMAS MERCH DROP!!🎄🎅❄️http://offlinetv.com/OfflineTV Roster:Scarra | https://twitter.com/scarraPokimane | https://twitter.com/pokimanelolLilyPichu ...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=llFT7vcp8o0",
      id: "llFT7vcp8o0",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/llFT7vcp8o0/maxresdefault.jpg",
      title: "12 year old kid breaks scoreboard",
      creator: "Unreal Baseball",
      views: 2110797,
      description: "",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=ng9dtd6qwuM",
      id: "ng9dtd6qwuM",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/ng9dtd6qwuM/maxresdefault.jpg",
      title: "AMONG US with CUSTOM SKIN (epic)",
      creator: "LazarBeam",
      views: 13441688,
      description:
        "AMONG US with a lazarbeam skincheckout ARKH - https://www.arkh.com/👕LAZAR Merch - https://shoplazar.com/🐤TWITTER - https://twitter.com/lazarbeam📘 FACEBOOK...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=qRRuOTuhL_o",
      id: "qRRuOTuhL_o",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/qRRuOTuhL_o/maxresdefault.jpg",
      title: "How Jawbreakers Are Made",
      creator: "Insider",
      views: 17623480,
      description:
        "Jawbreakers, also known as gobstoppers, are a popular candy  that originated in the United Kingdom. While the size of the candy ball varies, jawbreakers ofte...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=GOMkFOjROSg",
      id: "GOMkFOjROSg",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/GOMkFOjROSg/maxresdefault.jpg",
      title: "Ice Dropped Down Borehole in Antarctica Creates Unusual Sound",
      creator: "Storyful Rights Management",
      views: 10675621,
      description:
        "Dr. Peter Neff and a few other scientists decided to do an experiment and drop a piece of ice 90 meters down a borehole on Taylor Glacier in Antarctica to se...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=o0etimvtD74",
      id: "o0etimvtD74",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/o0etimvtD74/maxresdefault.jpg",
      title: "A 15-Year-Old Entrepreneur Impresses the Sharks - Shark Tank",
      creator: "ABC",
      views: 2716109,
      description:
        "Fifteen-year-old Carson Grill and his father Jason pitch their paint storage solution Touch Up Cup, and the Sharks can't stop marveling at Carson's business ...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=lvZBGJkbeTE",
      id: "lvZBGJkbeTE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/lvZBGJkbeTE/hqdefault.jpg",
      title: "Kid Wins Talent Show Dancing to Michael Jackson's Billie Jean",
      creator: "OpenMic Crew",
      views: 26351344,
      description:
        "Pitman High School Turlock Ca Teen Wins By A Mile As He Dances To Michael Jackson's Billy Jean.  (Brett Nichols)",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=cOU17LDTVNo",
      id: "cOU17LDTVNo",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/cOU17LDTVNo/maxresdefault.jpg",
      title: "Short Film: BLACK JOY IS MAGIC",
      creator: "Beleaf In Fatherhood",
      views: 404246,
      description:
        "In partnership with YouTube Originals’ #BearWitnessTakeAction 2: Continuing The Movement.Black Joy is Magic. It lights up the room and brings warmth to place...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=kmRhy2gLclI",
      id: "kmRhy2gLclI",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/kmRhy2gLclI/maxresdefault.jpg",
      title: "DeRay McKesson Talks Criminal Justice",
      creator: "YouTube Originals",
      views: 151824,
      description:
        "In partnership with YouTube Originals’ #BearWitnessTakeAction 2: Continuing The Movement.DeRay McKesson tackles the criminal justice system and focuses on th...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=QWdW2x_O6mQ",
      id: "QWdW2x_O6mQ",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/QWdW2x_O6mQ/maxresdefault.jpg",
      title: "What is Progress? // My Black Family Across 3 Generations",
      creator: "Hallease",
      views: 93387,
      description:
        "In partnership with YouTube Originals’ #Bear WitnessTakeAction 2: Continuing The Movement.What is progress? I find myself questioning that more and more as w...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=L_REGt4Vktk",
      id: "L_REGt4Vktk",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/L_REGt4Vktk/maxresdefault.jpg",
      title:
        "Having A Tough Conversation with My Mom - Nia Sioux I Bear Witness, Take Action 2",
      creator: "Nia Sioux",
      views: 57320,
      description:
        "In partnership with YouTube Originals’ #BearWitnessTakeAction 2: Continuing The Movement.My mom and I sat down to discuss some really important, and heavy to...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=jbX0TwPQ1Ew",
      id: "jbX0TwPQ1Ew",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/jbX0TwPQ1Ew/maxresdefault.jpg",
      title: "BWTA Radio hosted by Storm Reid as “DJ Jus-T-Ice. @StormReid",
      creator: "YouTube Originals",
      views: 18448,
      description:
        "Storm Reid joins the ranks of #Bear WitnessTakeAction 2 to discuss policy change, injustice, and calls for new leadership. She’s joined by actor Asante Black...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=ODeqcpWrx3o",
      id: "ODeqcpWrx3o",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/ODeqcpWrx3o/maxresdefault.jpg",
      title:
        "The generational curse no one talks about | Tarek Ali I Bear Witness, Take Action 2",
      creator: "Tarek Ali",
      views: 23862,
      description:
        "In partnership with YouTube Originals’ #BearWitnessTakeAction 2: Continuing The Movement.We all know what a generational curse is right? You know when Our fa...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=mbA1HobcD9I",
      id: "mbA1HobcD9I",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/mbA1HobcD9I/maxresdefault.jpg",
      title: "A New Modern Family",
      creator: "Team2Moms",
      views: 21830,
      description:
        "In partnership with YouTube Originals’ #BearWitnessTakeAction 2: Continuing The Movement. In this video, we wanted to share our journey of why representation...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=bGU6GNgFrhc",
      id: "bGU6GNgFrhc",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/bGU6GNgFrhc/maxresdefault.jpg",
      title: "Bear Witness, Take Action 2 - Official Trailer",
      creator: "YouTube Originals",
      views: 1303906,
      description:
        "We’ve marched. We’ve cried out for justice. We’ve raised our voices. What’s next? Join Common & Keke Palmer for #BearWitnessTakeAction 2: Continuing The Move...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=ZdfNUxI4xgI",
      id: "ZdfNUxI4xgI",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/ZdfNUxI4xgI/maxresdefault.jpg",
      title:
        "Gordon Ramsay Cooks For Cambodian Royalty | Gordon's Great Escape",
      creator: "Gordon Ramsay",
      views: 7052996,
      description:
        "As Gordon's trip comes to an end, he puts what he's learned to the test as he cooks for Cambodian royalty.#GordonRamsay #Cooking Gordon Ramsay’s Ultimate Coo...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=5qap5aO4i9A",
      id: "5qap5aO4i9A",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/5qap5aO4i9A/maxresdefault_live.jpg",
      title: "lofi hip hop radio - beats to relax/study to",
      creator: "ChilledCow",
      views: 327532182,
      description:
        "Thank you for listening, I hope you will have a good time here :)🎼 Listen to the playlist on Spotify, Apple music and more→ https://bit.ly/chilledcow-playli...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=WsptdUFthWI",
      id: "WsptdUFthWI",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/WsptdUFthWI/maxresdefault.jpg",
      title:
        "Closer - The Chainsmokers ft. Halsey (Boyce Avenue ft. Sarah Hyland cover) on Spotify & Apple",
      creator: "Boyce Avenue",
      views: 117458969,
      description:
        "Tickets + VIP Meet & Greets: http://smarturl.it/BATourSpotify: http://smarturl.it/CloserSpotifyBA2Apple: http://smarturl.it/CloserAppleBA2iTunes: http://smar...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=PmEJs9VS9jE",
      id: "PmEJs9VS9jE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/PmEJs9VS9jE/maxresdefault.jpg",
      title:
        "Dr. Vin Gupta Gets COVID-19 Vaccine On-Air: ‘This Is Going To Save Lives’ | TODAY",
      creator: "TODAY",
      views: 707942,
      description:
        "See NBC News medical contributor Dr. Vin Gupta and his colleague Dr. Eliot Fagley receive their COVID-19 vaccines live on-air. “This is the culmination of a ...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=S4mfSCtfKCA",
      id: "S4mfSCtfKCA",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/S4mfSCtfKCA/maxresdefault.jpg",
      title: "COVID-19 relief package deal on horizon",
      creator: "ABC News",
      views: 320983,
      description:
        "Congressional leaders say they are close to coming to a deal on COVID relief as cases around the nation soar.",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=WGBYBV2MPnI",
      id: "WGBYBV2MPnI",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/WGBYBV2MPnI/maxresdefault.jpg",
      title: "Hollywood reacts to Tom Cruise’s recorded COVID-19 tirade l GMA",
      creator: "Good Morning America",
      views: 2159548,
      description:
        "Stars like Whoopi Goldberg and George Clooney have offered support for the megastar, who was caught berating crew members for breaking health guidelines on t...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=R9P8PcuL6RU",
      id: "R9P8PcuL6RU",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/R9P8PcuL6RU/maxresdefault.jpg",
      title:
        "Emergency physician who treats COVID-19 patients says pulse oximeters are critical tool against v…",
      creator: "CBS This Morning",
      views: 143533,
      description:
        'Emergency medicine physician Dr. Richard Levitan explains why he believes pulse oximeters are so important to preventing COVID-19 deaths. Levitan joins "CBS ...',
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=EY-SSAljYa4",
      id: "EY-SSAljYa4",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/EY-SSAljYa4/maxresdefault.jpg",
      title:
        "Congress closes in on a $900 billion Covid-19 relief deal — Here's the latest",
      creator: "CNBC Television",
      views: 418805,
      description:
        "Congress is closing in on a $900 billion coronavirus relief deal and could announce it as soon as Wednesday. Top Republicans and Democrats negotiated a gover...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=s1EyijVNx2M",
      id: "s1EyijVNx2M",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/s1EyijVNx2M/maxresdefault.jpg",
      title:
        "Congress inching toward COVID-19 relief package, including stimulus checks",
      creator: "CBS News",
      views: 52777,
      description:
        "Democrats and Republicans have made concessions on a COVID-19 relief package, making the passage of a deal look more likely. CBS News chief congressional cor...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=hMrk1VNBub8",
      id: "hMrk1VNBub8",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/hMrk1VNBub8/maxresdefault.jpg",
      title: "The Country That Learned to Live With Covid-19",
      creator: "Bloomberg Quicktake",
      views: 266970,
      description:
        "As nations around the world still struggle to contain Covid-19, South Korea’s early, focused, and perhaps controversial approach has kept loss of life and ec...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=ESe380Q9New",
      id: "ESe380Q9New",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/ESe380Q9New/maxresdefault.jpg",
      title:
        "California starts administering COVID-19 vaccine; more doses expected to arrive next week",
      creator: "KTLA 5",
      views: 40672,
      description:
        "With statewide distribution of the first batch of COVID-19 vaccine doses underway, Gov. Gavin Newsom announced Tuesday that California is getting another 393...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=dysdU3zFOnE",
      id: "dysdU3zFOnE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/dysdU3zFOnE/maxresdefault.jpg",
      title: "California requests 5,000 more body bags as COVID-19 cases surge",
      creator: "Los Angeles Times",
      views: 121729,
      description:
        "Tuesday's statewide COVID-19 death toll was higher than the record tally set only a week ago.SUBSCRIBE FOR MORE VIDEOS AND NEWShttp://www.youtube.com/subscri...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=CGg8FzDAt9w",
      id: "CGg8FzDAt9w",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/CGg8FzDAt9w/maxresdefault.jpg",
      title: "Congress considers COVID-19 relief bill l WNT",
      creator: "ABC News",
      views: 232779,
      description:
        "Democratic and Republican leaders said that a COVID-19 relief bill is on the way, as more than 19 million Americans collect unemployment benefits.WATCH THE F...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=jXZAbnn1kTU",
      id: "jXZAbnn1kTU",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/jXZAbnn1kTU/hqdefault.jpg",
      title:
        "Ambient Study Music To Concentrate - 4 Hours of Music for Studying, Concentration and Memory",
      creator: "Quiet Quest - Study Music",
      views: 3174999,
      description:
        "Keep focused with this ambient study music to concentrate by Quiet Quest - Study Music.Play this instrumental music in the background and use it as concentra...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=2Ieg3yFcaaw",
      id: "2Ieg3yFcaaw",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/2Ieg3yFcaaw/maxresdefault.jpg",
      title:
        "Christmas Acoustic Guitar Fireplace with Music & Crackling - 4K - Cozy Christmas Ambience",
      creator: "Relax with TV Backgrounds",
      views: 3918913,
      description:
        "(Links for more of my Christmas Ambience TV Backgrounds below)Enjoy a relaxing acoustic Christmas guitar fireplace with traditional Christmas music. This sof...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=RyHo15EyGcE",
      id: "RyHo15EyGcE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/RyHo15EyGcE/maxresdefault.jpg",
      title:
        "The Return of Mr Bean | Episode 2 | Widescreen Version | Classic Mr Bean",
      creator: "Classic Mr Bean",
      views: 11012002,
      description:
        "Bean busks to pay a busker (Dave O'Higgins), tries out his new credit card in a department store, visits a restaurant and is served an unwanted dish, leading...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=1mI3vkuIEj8",
      id: "1mI3vkuIEj8",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/1mI3vkuIEj8/maxresdefault.jpg",
      title:
        "Freddie Highmore Answers the Web's Most Searched Questions | WIRED",
      creator: "WIRED",
      views: 8735924,
      description: `"The Good Doctor" star Freddie Highmore answers the internet's most searched questions about himself. Is Freddie Highmore English? Was Freddie in Harry Potte...`,
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=lA1ItxM9yIE",
      id: "lA1ItxM9yIE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/lA1ItxM9yIE/maxresdefault.jpg",
      title:
        "Rainy Night and Coffee Shop Ambience with Rain Sounds & Relaxing Jazz Music",
      creator: "Cozy Rain",
      views: 3135290,
      description:
        "Enjoy this relaxing Coffee Shop Ambience to watching and listening smooth jazz music playing in the background with rain sounds at night. This relaxing jazz ...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=RRcgqBNuoXc",
      id: "RRcgqBNuoXc",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/RRcgqBNuoXc/maxresdefault.jpg",
      title: "WORLD'S CHEAPEST FIRST CLASS AIRPLANE SEAT (Only $355)",
      creator: "LivingBobby",
      views: 8475514,
      description:
        "This is the world's cheapest first class airplane seat that I found after hours of research! Throughout this video, I do a flight review on this first class ...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=_77HS_NS4Co",
      id: "_77HS_NS4Co",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/_77HS_NS4Co/maxresdefault.jpg",
      title: "SEASON 8 OOF",
      creator: "Fe4RLess",
      views: 33943182,
      description:
        "thanks for watching.https://www.instagram.com/fe4rr/Outro Song: Josh A - No Chill",
      durationSeconds: undefined,
    },
    {id: "nYn1RZR_ph4", errorMessage: "Video does not exist"},
    {
      link: "https://www.youtube.com/watch?v=N8lCEJo1y5g",
      id: "N8lCEJo1y5g",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/N8lCEJo1y5g/maxresdefault.jpg",
      title: "Making a squirrel laugh",
      creator: "Cathy H",
      views: 5299512,
      description:
        "Tickling & wrestling Rocky at 8 months old. She LOVES alot of TLC.",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=bUvZNpFLtGs",
      id: "bUvZNpFLtGs",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/bUvZNpFLtGs/maxresdefault.jpg",
      title: "A Navy SEAL Explains Why You Should End A Shower With Cold Water",
      creator: "Business Insider",
      views: 11963545,
      description: `Former Navy SEAL Clint Emerson, author of "100 Deadly Skills: The SEAL Operative's Guide to Eluding Pursuers, Evading Capture, and Surviving Any Dangerous Si...`,
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=tA5giyG8E7g",
      id: "tA5giyG8E7g",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/tA5giyG8E7g/hqdefault.jpg",
      title: 'Henry Thomas audition för E.T. "Ok kid, you got the job".',
      creator: "UniversalPicsSweden",
      views: 20620788,
      description:
        "E.T. The Extra-Terrestrial släpps på Blu-ray för första gången 31 oktober. I restaurerat skick med nytt bonusmaterial.",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=bVq7snH0ulo",
      id: "bVq7snH0ulo",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/bVq7snH0ulo/hqdefault.jpg",
      title: "Kitchen Nightmares - Season 1 Episode 21 - Full Episode",
      creator: "Kitchen Nightmares - Full Episodes",
      views: 731364,
      description:
        "Chef Ramsay travels to Los Angeles, California to inspect Sante La Brea. He discovers a financially strapped restaurant owner who isn't respected by his staf...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=6L-WhdPBaiE",
      id: "6L-WhdPBaiE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/6L-WhdPBaiE/hqdefault.jpg",
      title:
        "Usain Bolt Wins 200m at 2011 World Championships  in 19.40 seconds",
      creator: "Franz Hoilett",
      views: 18626955,
      description:
        "Join Over 300,000 JAMAICANS! on http://www.facebook.com/IamaJamaicanUsain Bolt put his 100m nightmare behind him to claim gold in the 200m final at the world...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=UgHKb_7884o",
      id: "UgHKb_7884o",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/UgHKb_7884o/maxresdefault.jpg",
      title:
        "12 HOURS of Relaxing Fireplace Sounds - Burning Fireplace & Crackling Fire Sounds (NO MUSIC)",
      creator: "Cat Trumpet",
      views: 12438900,
      description:
        "Enjoy 12 hours of relaxing fireplace sounds! This burning fireplace features crackling fire sounds. Ideal for deep sleep, relaxation, meditation and study.#f...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=0MW0mDZysxc",
      id: "0MW0mDZysxc",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/0MW0mDZysxc/maxresdefault.jpg",
      title: "*teleports behind you*",
      creator: "Sh0gun",
      views: 46324835,
      description:
        "Source audio is from the anime Fist of the North StarSource for the video:https://www.youtube.com/watch?v=QCqxOzKNFks&feature=youtu.be%EF%BB%BFsay anything.....",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=z5LS4kqJjKo",
      id: "z5LS4kqJjKo",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/z5LS4kqJjKo/maxresdefault.jpg",
      title: "We Made Among Us Sounds Into a Song",
      creator: "Sheet Music Boss",
      views: 12053124,
      description:
        "☢ Reactor Meltdown in 3... 2... 1... ☢ Among Us SFX + Samplers = Win ✅After seeing Davie504's Among Us song, we had to make our own!Learn piano with Skoove: ...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=sjoepLlVL6o",
      id: "sjoepLlVL6o",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/sjoepLlVL6o/maxresdefault.jpg",
      title: "Curious Baby Seal Approaches Cameraman",
      creator: "I Watch You From Afar",
      views: 17043901,
      description:
        "Seal nom noms.Video owned and monetised by Junkin MediaReuploaded with permission",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=shoVsQhou-8",
      id: "shoVsQhou-8",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/shoVsQhou-8/maxresdefault.jpg",
      title: "6 Hours Mozart for Studying, Concentration, Relaxation",
      creator: "HALIDONMUSIC",
      views: 14984301,
      description:
        '🎧 Listen to our playlist on Spotify: http://bit.ly/MozartBrainPower🎬 Watch Hollywood Award-Winning Film "Interlude in Prague", Mozart in love: https://bit....',
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=2-Sw86fddpY",
      id: "2-Sw86fddpY",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/2-Sw86fddpY/maxresdefault.jpg",
      title: "Little Girl Thinks Stranger Is Santa",
      creator: "DailyPicksandFlicks",
      views: 11786494,
      description:
        "When this little girl went shopping, she got the surprise of her life when she saw Santa Claus browsing the aisles. She hurriedly went up to him and asked hi...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=KW8fGRTFWKc",
      id: "KW8fGRTFWKc",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/KW8fGRTFWKc/maxresdefault.jpg",
      title: "TOM AND JERRY Official Trailer (2021)",
      creator: "Movie Trailers Source",
      views: 11630284,
      description:
        "First trailer for Tom and Jerry starring Chloë Grace Moretz.",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=wlsdMpnDBn8",
      id: "wlsdMpnDBn8",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/wlsdMpnDBn8/maxresdefault.jpg",
      title: "Timber | A Chill Mix",
      creator: "Koala Kontrol",
      views: 31699815,
      description:
        "• check out my indie electronic spotify playlist - http://spoti.fi/293vj6r #timber #chillmix #chillmusic'Timber' is a new chill mix for 2016.  It includes so...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=B5E3IKF9HPs",
      id: "B5E3IKF9HPs",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/B5E3IKF9HPs/maxresdefault.jpg",
      title: "Tik Toks That Are Actually Relatable",
      creator: "SSSniperWolf",
      views: 16664710,
      description:
        "Tik Toks That Are Actually Relatable! Leave a Like if you enjoyed and can relate to some of these tiktok memes! Watch the last vid https://youtu.be/ULNFHKeD9...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=hgdSJdeGF_0",
      id: "hgdSJdeGF_0",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/hgdSJdeGF_0/maxresdefault.jpg",
      title: "Minecraft Speedrunner VS 3 Hunters FINALE",
      creator: "Dream",
      views: 50462497,
      description:
        "Minecraft Speedrunner VS 3 Hunters FINALE. This was insane.Patreon (Plugin): https://www.patreon.com/DreamWasTakenFollow my socials:➽ Twitter - @dreamwastake...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=WRC78QhtCbE",
      id: "WRC78QhtCbE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/WRC78QhtCbE/maxresdefault.jpg",
      title: "🥑 Avocado Tree from Seed in Water ( 60 Days Time-Lapse )",
      creator: "Seemingly Forever Timelapse",
      views: 1753203,
      description:
        "Enjoy this Sprouting Avocado Time-Lapse video. It is about how to grow an avocado tree from seed. Put an avocado seed into a pot of water and just be patient...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=48CuhRAjLyE",
      id: "48CuhRAjLyE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/48CuhRAjLyE/maxresdefault_live.jpg",
      title:
        "Instrumental Christmas Music with Fireplace 24/7 • Merry Christmas!",
      creator: "Soothing Relaxation",
      views: 6806999,
      description:
        "Instrumental Christmas music with a fireplace's crackling fire sounds 24/7. We wish you a Merry Christmas with these traditional Christmas songs, arranged by...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=88aDJFdUjH4",
      id: "88aDJFdUjH4",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/88aDJFdUjH4/maxresdefault.jpg",
      title:
        "Gordon Ramsay Is Stunned by Farmed Caviar; Makes Lobster & Caviar Salad",
      creator: "Gordon Ramsay",
      views: 52657036,
      description:
        "Gordon heads to Spain to visit a sustainable sturgeon farm, and experiences first hand how much caviar Can be produced from just one fish. He then whips up a...",
      durationSeconds: undefined,
    },
    {
      link: "https://www.youtube.com/watch?v=BUxBP0zS1pE",
      id: "BUxBP0zS1pE",
      recommendationCount: null,
      thumbnailUrl: "https://i.ytimg.com/vi/BUxBP0zS1pE/maxresdefault.jpg",
      title: 'NFL "How Are You in the NFL?" Moments',
      creator: "Highlight Heaven",
      views: 1331432,
      description:
        'Some of the dumbest and most confusing plays in NFL history that make you wonder "how are you in the NFL?"Comment some more for part 2!Discord Server: https:...',
      durationSeconds: undefined,
    },
  ],
};
